# Generated by Django 2.2.14 on 2023-11-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231116_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F1', 'Food 1'), ('F2', 'Food 2'), ('F3', 'Food 3')], max_length=2),
        ),
    ]
